### PR TITLE
Update/sdkv3

### PR DESCRIPTION
**Pull request by ff6347**
I succesfully tested the v3 on MacOS. This PR
- adds the library v3 for linux and macos 
- updates the source to reflect the v3 SDK

### CODE REVIEW

**Comment by thomasgeissl** [comment]
I had some hard time merging the master. I have tested it on osx 10.13, Makefiles. Would you mind double checking on your side again?

**Comment by ff6347** [comment]
Works on MacOS 10.14 with of_v0.10.1_osx_release. 👍

**Comment by thomasgeissl** [comment]
muchas gracias fabian

**Comment by ff6347** [comment]
De nada. 🙃

**Pull request merged**
